name: Build Firmware

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone SonixQMK
        run: git clone https://github.com/SonixQMK/qmk_firmware.git
      - name: Install qmk deps
        run: cd qmk_firmware && ./util/qmk_install.sh && python3 -m pip install qmk
      - name: fix gcc
        run: sudo bash .github/scripts/update-gcc10-ubuntu.sh
      - name: Install git submodules
        run: cd qmk_firmware && make git-submodule
      - name: Copy custom keymaps
        run: cp -rp keyboards/keychron/k3/keymaps/iso_seyahdoo qmk_firmware/keyboards/keychron/k3/keymaps
      - name: Compile firmware
        run: cd qmk_firmware && make keychron/k3/rgb/optical_iso:iso_seyahdoo
      - name: Upload compiled firmware (build artifact)
        uses: actions/upload-artifact@v2
        with:
          name: Keychron K3 QMK Firmware
          path: qmk_firmware/keychron_k3_rgb_optical_iso_iso_seyahdoo.bin
      - name: Upload compiled firmware (tagged release)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            qmk_firmware/keychron_k3_rgb_optical_iso_iso_seyahdoo.bin
    # runs-on: macos-11
    # steps:
    #   - uses: actions/checkout@v2
    #   - name: Install qmk
    #     run: brew install qmk/qmk/qmk
    #   - name: Install arm-gcc 10
    #     run: brew install arm-gcc-bin@10
    #   - name: Install avr-gcc 8
    #     run: brew link --force avr-gcc@8
    #   - name: Clone SonixQMK
    #     run: git clone https://github.com/SonixQMK/qmk_firmware.git
    #   - name: Install QMK pip dependencies
    #     run: cd qmk_firmware && python3 -m pip install -r requirements.txt
    #   - name: Install git submodules
    #     run: cd qmk_firmware && make git-submodule
    #   - name: Copy custom keymaps
    #     run: cp -rp keymaps qmk_firmware/keyboards/keychron/k6/keymaps/ansi-josh
    #   - name: Compile firmware
    #     run: cd qmk_firmware && make keychron/k6:ansi-josh
    #   - name: Upload compiled firmware
    #     uses: softprops/action-gh-release@v1
    #     if: startsWith(github.ref, 'refs/tags/')
    #     with:
    #       files: |
    #         qmk_firmware/keychron_k6_ansi-josh.bin
